### ISSUE TITLE
SameSite cookie patch: `Undefined index: samesite`

### ISSUE THREAD

**Issue by Leksat** [amazeeio-solutions/silverback-mono#733]
Every request create a log record for this notice. Drupal log becomes full really quick.

Example record from a project:
```
Notice: Undefined index: samesite in Drupal\Core\Session\SessionConfiguration->getOptions() (line 56 of /app/apps/cms/web/core/lib/Drupal/Core/Session/SessionConfiguration.php)
#0 /app/apps/cms/web/core/includes/bootstrap.inc(312): _drupal_error_handler_real(8, 'Undefined index...', '/app/apps/cms/w...', 56)
#1 /app/apps/cms/web/core/lib/Drupal/Core/Session/SessionConfiguration.php(56): _drupal_error_handler(8, 'Undefined index...', '/app/apps/cms/w...', 56, Array)
#2 /app/apps/cms/web/core/lib/Drupal/Core/Session/SessionManager.php(103): Drupal\Core\Session\SessionConfiguration->getOptions(Object(Symfony\Component\HttpFoundation\Request))
#3 /app/apps/cms/vendor/symfony/http-foundation/Session/Session.php(57): Drupal\Core\Session\SessionManager->start()
#4 /app/apps/cms/web/core/lib/Drupal/Core/StackMiddleware/Session.php(53): Symfony\Component\HttpFoundation\Session\Session->start()
#5 /app/apps/cms/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /app/apps/cms/vendor/asm89/stack-cors/src/Asm89/Stack/Cors.php(49): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /app/apps/cms/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Asm89\Stack\Cors->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /app/apps/cms/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /app/apps/cms/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /app/apps/cms/web/core/lib/Drupal/Core/DrupalKernel.php(716): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /app/apps/cms/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#12 {main}
```

**Comment by pmelab** [comment]
Samesite patch is not needed any more because we run front- and backends on the same apex domain.
